ANN USING BACK PROPAGATION

In [5]:
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Input
from tensorflow.keras.utils import to_categorical
import numpy as np

#load the data
(X_train,y_train),(X_test,y_test)=fashion_mnist.load_data()




29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [7]:
from sklearn.metrics import classification_report,confusion_matrix

In [8]:
#Normalize the data
X_train=X_train/255.0
X_test=X_test/255.0

In [11]:
#Reshape the data from  (28,28) to(784,)
X_train=X_train.reshape(X_train.shape[0],-1)
X_test=X_test.reshape(X_test.shape[0],-1)

In [12]:
#one hot encode lables
y_train=to_categorical(y_train,10)
y_test=to_categorical(y_test,10)

In [13]:
#build the model
model=Sequential([
        Input(shape=(784,)),
        Dense(128,activation='relu'),
        Dropout(0.2),
        Dense(10,activation='softmax'),
])



In [14]:
#compile the model
model.compile(optimizer='adam',
             loss='categorical_crossentropy',
             metrics=['accuracy'])

In [15]:
#train the model
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.5805 - loss: 8.9642 - val_accuracy: 0.6261 - val_loss: 0.9314
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6363 - loss: 0.9391 - val_accuracy: 0.7008 - val_loss: 0.7983
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6555 - loss: 0.8495 - val_accuracy: 0.7257 - val_loss: 0.7172
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6819 - loss: 0.8150 - val_accuracy: 0.7437 - val_loss: 0.6454
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6940 - loss: 0.7960 - val_accuracy: 0.7532 - val_loss: 0.6685


In [16]:
#evaluate the model
test_loss,test_accuracy=model.evaluate(X_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7547 - loss: 0.6824


In [17]:
print(test_accuracy)


0.7531999945640564


In [18]:
#predict the labels for the test set
y_pred=model.predict(X_test)
y_pred_classes=np.argmax(y_pred,axis=1)
y_true=np.argmax(y_test,axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [19]:
#print confusion matrix
conf_matrix=confusion_matrix(y_true,y_pred_classes)
print(conf_matrix)

[[513   3   8  41   2   1 410   1  21   0]
 [  0 950   6  27   2   0  14   0   1   0]
 [  3   1 306   8 479   1 190   0  12   0]
 [  6  17   6 834  10   0 122   0   5   0]
 [  1   1 123  47 762   0  60   0   6   0]
 [  0   0   0   0   0 894   2  64   7  33]
 [ 52   1 250  22 182   0 459   0  34   0]
 [  0   0   0   0   0  17   0 945   0  38]
 [  3   1   0  10   2   6  26   3 948   1]
 [  1   0   0   0   0  32   1  45   0 921]]


In [ ]:
#print classification report
class_report=classification_report(y_true,y_pred_classes,)